# {{ project_name_short }}:
#   metadata:
#     description: "Kria design for ACORN RaPR"
#     author: "The DIS team"
#     division: "CSAID/RTPS/DIS"
#     vhdl_standard: "08"
#     copyright: "Copyright (c) 2025 Fermi Forward Discovery Group, LLC"
#   spec: "../../spec/ACORN_RaPR_Pinout.xlsx"

Llcoolj:
  metadata:
    description: "LLCOOLJ -- Artix-only variant"
    author: "The DIS team"
    division: "CSAID/RTPS/DIS"
    vhdl_standard: "08"
    copyright: "Copyright (c) 2025 Fermi Forward Discovery Group, LLC"
  spec: "LLCOOLJ Pinouts and Addresses.xlsx"
