--
-- THIS FILE HAS BEEN AUTOGENERATED AND DERIVES FROM FILES IN spec
--
--
{% extends "bits/header.vhd" %}

{% block content %}
library ieee;
use ieee.std_logic_1164.all;

{% if vendor == 'Xilinx' %}
library unisim;
use unisim.vcomponents.all;
{% endif %}

use work.pkg_{{ project_name }}.t_{{ project_name_short }};

-- Extra libraries
{% block extra_libraries %}
{% endblock  %}

entity top is

port(

  -- Extra ports
{% block extra_ports %}
{% endblock %}

    -- Differential ports
{% for idx, port in diff_ports.iterrows() %}
  io_{{ (port['Net Name'] ~ '_p').ljust(50) }} : {{ port['DIR'].lower().ljust(3) }} std_logic;
  io_{{ (port['Net Name'] ~ '_n').ljust(50) }} : {{ port['DIR'].lower().ljust(3) }} std_logic;
{% endfor %}

    -- Single ended ports
{% for idx, port in single_ended_ports.iterrows() %}
  io_{{ port['Net Name'].ljust(50) }} : {{ port['DIR'].lower().ljust(3) }} std_logic
  {%- if idx < (single_ended_ports | length) - 1 %};    {% else %}     {% endif -%}
    -- {{ port['Notes'] }}
{% endfor %}
);

end entity top;

architecture rtl of top is

  -- Main container for project's specification signals
  signal sig_{{ project_name_short }} : t_{{ project_name_short }};

  -- Extra architecture declarations
{% block extra_architecture_declaration %}
{% endblock %}

begin

  main : entity work.main
    port map(
{% block extra_main_portmap %}
{% endblock %}
      if_{{ project_name_short }} => sig_{{ project_name_short }}
    );


  -- Extra architecture
{% block extra_architecture %}
{% endblock %}

-- Assignments to main record

-- Inputs
{% for idx, port in single_ended_ports[single_ended_ports["DIR"]=="IN"].iterrows() %}
  {{ port["var_sig"].ljust(60) }} <= {{ port["var_io"] }};
{% endfor %}

-- Outputs
{% for idx, port in single_ended_ports[single_ended_ports["DIR"]=="OUT"].iterrows() %}
{% if port['Differential'] != True %}
  {{ port["var_io"].ljust(60) }} <= {{ port["var_sig"] }};
{% endif %}
{% endfor %}

-- Inouts
{% for idx, port in single_ended_ports[single_ended_ports["DIR"]=="INOUT"].iterrows() %}
  {{ port["var_io"].ljust(60) }} <= {{ port["var_sig"] }};
{% endfor %}

-- Differential input buffers
{% for idx, port in diff_ports[diff_ports["DIR"] == "IN"].iterrows() %}
{% if port['Transceiver'] == False %}
ibuf_{{ port['Net Name'] }} : IBUFDS
   port map(
     o  => {{ port["var_sig"] }},
     i  => {{ port["var_io"] }}_p,
     ib => {{ port["var_io"] }}_n
  );
{% endif %}
{% endfor %}

-- Differential input buffers (Transceivers)
{% for idx, port in diff_ports[diff_ports["DIR"] == "IN"].iterrows() %}
{% if port['Transceiver'] == True %}
ibuf_{{ port['Net Name'] }} : IBUFDS_GTE2
   port map(
     o  => {{ port["var_sig"] }},
     odiv2 => open,
     ceb => '0',
     i  => {{ port["var_io"] }}_p,
     ib => {{ port["var_io"] }}_n
  );
{% endif %}
{% endfor %}

-- Differential output buffers

{% for idx, port in diff_ports[diff_ports["DIR"] == "OUT"].iterrows() %}
{% if port['Differential'] == True %}
obuf_{{ port['Net Name'] }} : OBUFDS
   port map(
     i  => {{ port["var_sig"] }},
     o  => {{ port["var_io"] }}_p,
     ob => {{ port["var_io"] }}_n
  );
{% endif %}
{% endfor %}

end architecture rtl;

{% endblock %}
