--
-- THIS FILE HAS BEEN AUTOGENERATED AND DERIVES FROM FILES IN spec
--
--
{% extends "bits/header.vhd" %}

{% block content %}
library ieee;
use ieee.std_logic_1164.all;

{% if spec.project.vendor == 'Xilinx' %}
library unisim;
use unisim.vcomponents.all;
{% endif %}

use work.{{ spec.project.package_name }}.{{ spec.project.supertype_name }};

-- Extra libraries
{% block extra_libraries %}
{% endblock  %}

entity top is

port(

  -- Extra ports
{% block extra_ports %}
{% endblock %}

    -- Differential ports
{% for port in spec.all_signals_differential %}
  {{ (port.name_io ~ '_p').ljust(50) }} : {{ port.direction.ljust(3) }} std_logic;
  {{ (port.name_io ~ '_n').ljust(50) }} : {{ port.direction.ljust(3) }} std_logic;
{% endfor %}

    -- Single ended ports
{% for port in spec.all_signals_singleended %}
  {{ port.name_io.ljust(50) }} : {{ port.direction.ljust(3) }} std_logic
  {%- if loop.last %}    {% else %};    {% endif -%}
    -- {{ port['Notes'] }}
{% endfor %}
);

end entity top;

architecture rtl of top is

  -- Main container for project's specification signals
  signal sig_{{ spec.project.name_short }} : {{ spec.project.supertype_name }};

  -- Extra architecture declarations
{% block extra_architecture_declaration %}
{% endblock %}

begin

  main : entity work.main
    port map(
{% block extra_main_portmap %}
{% endblock %}
      if_{{ spec.project.name_short }} => sig_{{ spec.project.name_short }}
    );


  -- Extra architecture
{% block extra_architecture %}
{% endblock %}

-- Assignments to main record

-- Inputs
{% for port in spec.all_signals_singleended if port.direction == 'in' and not (port.name.endswith('_N') and (spec.all_signals_differential | selectattr('bundle_name', 'equalto', port.bundle_name) | selectattr('name', 'equalto', port.name[:-2]) | list | length)) %}
  {{ port.name_signalinbundle.ljust(60) }} <= {{ port.name_io }};
{% endfor %}

-- Outputs
{% for port in spec.all_signals_singleended if port.direction == 'out' and not (port.name.endswith('_N') and (spec.all_signals_differential | selectattr('bundle_name', 'equalto', port.bundle_name) | selectattr('name', 'equalto', port.name[:-2]) | list | length)) %}
{% if not port.Differential %}
  {{ port.name_io.ljust(60) }} <= {{ port.name_signalinbundle }};
{% endif %}
{% endfor %}

-- Inouts
{% for port in spec.all_signals_singleended if port.direction == 'inout' and not (port.name.endswith('_N') and (spec.all_signals_differential | selectattr('bundle_name', 'equalto', port.bundle_name) | selectattr('name', 'equalto', port.name[:-2]) | list | length)) %}
  {{ port.name_io.ljust(60) }} <= {{ port.name_signalinbundle }};
{% endfor %}

-- Differential input buffers
{% for port in spec.all_signals_differential if port.direction == 'in'%}
{% if not port.Transceiver  %}
{% set dup_name = (spec.all_signals_differential | selectattr('name', 'equalto', port.name) | list | length) > 1 %}
ibuf_{% if dup_name %}{{ port.bundle_name }}_{% endif %}{{ port.name }} : IBUFDS
   port map(
     o  => {{ port.name_signalinbundle }},
     i  => {{ port.name_io }}_p,
     ib => {{ port.name_io }}_n
  );
{% endif %}
{% endfor %}

-- Differential input buffers (Transceivers)
{% for port in spec.all_signals_differential if port.direction == 'in'%}
{% if port.is_transceiver %}
{% set dup_name = (spec.all_signals_differential | selectattr('name', 'equalto', port.name) | list | length) > 1 %}
ibuf_{% if dup_name %}{{ port.bundle_name }}_{% endif %}{{ port.name }} : IBUFDS_GTE2
   port map(
     o  => {{ port.name_signalinbundle }},
     odiv2 => open,
     ceb => '0',
     i  => {{ port.name_io }}_p,
     ib => {{ port.name_io }}_n
  );
{% endif %}
{% endfor %}

-- Differential output buffers

{% for port in spec.all_signals_differential if port.direction == 'out'%}
{% set dup_name = (spec.all_signals_differential | selectattr('name', 'equalto', port.name) | list | length) > 1 %}
obuf_{% if dup_name %}{{ port.bundle_name }}_{% endif %}{{ port.name }} : OBUFDS
   port map(
     i  => {{ port.name_signalinbundle }},
     o  => {{ port.name_io }}_p,
     ob => {{ port.name_io }}_n
  );
{% endfor %}

end architecture rtl;

{% endblock %}
